"""Lib Tests Test Agent Pointers.

Copyright (c) 2025 MCB Contributors. All rights reserved.
SPDX-License-Identifier: MIT
"""
from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MODULE_PATH = ROOT / "scripts" / "lib" / "agent_pointers.py"
SPEC = importlib.util.spec_from_file_location("mcb_agent_pointers", MODULE_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"failed to load module spec for {MODULE_PATH}")
agent_pointers = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(agent_pointers)


class AgentPointerTests(unittest.TestCase):
    def test_all_rendered_pointers_reference_agents_ssot(self) -> None:
        for path, content in agent_pointers.render_all().items():
            with self.subTest(path=path):
                self.assertIn("AGENTS.md", content)
                self.assertIn("generated by `make gen-agent-pointers`", content)
                self.assertNotIn("Architecture Violation Codes", content)
                self.assertNotIn("Forbidden Patterns", content)
                self.assertNotIn("Quick Reference", content)

    def test_rendered_pointer_files_are_not_ignored(self) -> None:
        ignored = {
            line.strip()
            for line in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }

        for path in agent_pointers.render_all():
            with self.subTest(path=path):
                self.assertNotIn(path, ignored)

    def test_check_detects_drift_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "AGENTS.md").write_text("# AGENTS\n", encoding="utf-8")
            first_path = next(iter(agent_pointers.render_all()))
            pointer_path = root / first_path
            pointer_path.parent.mkdir(parents=True, exist_ok=True)
            pointer_path.write_text("stale\n", encoding="utf-8")

            result = agent_pointers.sync(root, check=True)

            self.assertEqual([first_path], result.changed_paths[:1])
            self.assertEqual("stale\n", pointer_path.read_text(encoding="utf-8"))

    def test_sync_writes_all_pointer_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "AGENTS.md").write_text("# AGENTS\n", encoding="utf-8")

            result = agent_pointers.sync(root, check=False)

            self.assertEqual(set(agent_pointers.render_all()), set(result.changed_paths))
            for path, expected in agent_pointers.render_all().items():
                self.assertEqual(expected, (root / path).read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
