"""Lib Agent Pointers.

Copyright (c) 2025 MCB Contributors. All rights reserved.
SPDX-License-Identifier: MIT
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import NamedTuple

GENERATED = "<!-- generated by `make gen-agent-pointers`; source: AGENTS.md -->"


class SyncResult(NamedTuple):
    changed_paths: list[str]


def _pointer(title: str, agents_path: str) -> str:
    return (
        f"{GENERATED}\n"
        f"# {title}\n\n"
        f"`{agents_path}` is the project single source of truth for all agent rules,\n"
        "architecture, commands, beads workflow, validation, and Git policy.\n\n"
        "Do not duplicate those rules here. Update `AGENTS.md`, then run\n"
        "`make gen-agent-pointers`.\n"
    )


def _frontmatter_pointer(title: str, agents_path: str, frontmatter: str) -> str:
    return f"{frontmatter}\n{_pointer(title, agents_path)}"


def render_all() -> dict[str, str]:
    return {
        "CLAUDE.md": (
            f"{GENERATED}\n"
            "# CLAUDE.md — MCB Project Instructions\n\n"
            "Reference [`./AGENTS.md`](./AGENTS.md) for all project rules,\n"
            "architecture, commands, beads workflow, validation, and Git policy.\n"
            "Do not duplicate those rules here.\n\n"
            "<!-- bd-doctor-divergence: ok -->\n"
            "<!-- Intentional: this file is a generated thin pointer to AGENTS.md. -->\n"
        ),
        "GEMINI.md": _pointer("GEMINI.md — MCB Project Instructions", "./AGENTS.md"),
        ".clinerules": _pointer("MCB — Cline Rules", "AGENTS.md"),
        ".windsurfrules": _pointer("MCB — Windsurf Rules", "AGENTS.md"),
        "CONVENTIONS.md": _pointer("MCB — Conventions (Aider)", "AGENTS.md"),
        "codex.md": _pointer("Codex Instructions — MCB", "AGENTS.md"),
        ".github/copilot-instructions.md": _pointer(
            "Copilot Instructions — MCB",
            "../AGENTS.md",
        ),
        ".continue/rules/mcb.md": _frontmatter_pointer(
            "MCB — Continue.dev Rules",
            "../../AGENTS.md",
            '---\nname: MCB Project Rules\nglobs: ["**/*.rs", "**/*.toml", "**/*.md"]\n---',
        ),
        ".cursor/rules/mcb.mdc": _frontmatter_pointer(
            "MCB — Cursor AI Rules",
            "../../AGENTS.md",
            (
                "---\n"
                "description: MCB project rules for Cursor AI\n"
                'globs: ["**/*.rs", "**/*.toml", "**/*.md"]\n'
                "alwaysApply: true\n"
                "---"
            ),
        ),
        ".gemini/styleguide.md": (
            f"{GENERATED}\n"
            "# MCB — Gemini Code Assist Style Guide\n\n"
            "Single source of truth: [`AGENTS.md`](../AGENTS.md). This file only\n"
            "adds Gemini-specific review ordering and must not restate project rules.\n\n"
            "## PR Review Priorities\n\n"
            "1. Architecture boundaries\n"
            "2. Safety\n"
            "3. Correctness\n"
            "4. Performance\n"
            "5. Maintainability\n"
            "6. Security\n"
            "7. Tests\n"
        ),
    }


def sync(root: Path, *, check: bool) -> SyncResult:
    agents = root / "AGENTS.md"
    if not agents.is_file():
        raise FileNotFoundError(f"missing SSOT: {agents}")

    changed_paths: list[str] = []
    for relative_path, expected in render_all().items():
        path = root / relative_path
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        changed_paths.append(relative_path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    return SyncResult(changed_paths)


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize generated agent pointer files.")
    parser.add_argument("--check", action="store_true", help="fail if any pointer is out of sync")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="workspace root")
    args = parser.parse_args()

    result = sync(args.root.resolve(), check=args.check)
    if result.changed_paths:
        action = "out of sync" if args.check else "updated"
        for path in result.changed_paths:
            print(f"{action}: {path}")
        return 1 if args.check else 0

    print("agent pointers in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
